name: ddmind-finlora-mps
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - ipykernel
  - ipywidgets
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - pyarrow
  - requests
  - tqdm
  - traitlets
  - typing-extensions
  - matplotlib-inline
  - aiohttp
  - dill
  - psutil
  - filelock
  - ipython
  - protobuf
  - pyyaml
  - regex
  - tokenizers
  - transformers
  - datasets
  - rich

  - pip:
      # Setup.sh safe pip packages
      - accelerate
      - peft
      - tensorboard
      - ninja
      - werkzeug
      - markdown
      - hjson
      - pydantic
      - pydantic-core
      - types-python-dateutil
      - uri-template
      - webcolors
      - jsonpointer
      - grpcio
      - fqdn
      - isoduration
      - wandb
      - python-dotenv
      - fireworks-ai

      # Sphinx docs (from requirements.txt)
      - nbsphinx==0.9.6
      - nbsphinx-link==1.3.1
      - sphinx-autobuild==2024.10.3
      - sphinx_design==0.6.1
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
