name: ddmind-finlora
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - ipykernel
  - ipywidgets
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - pyarrow
  - requests
  - tqdm
  - traitlets
  - typing-extensions
  - matplotlib-inline
  - aiohttp
  - dill
  - psutil
  - filelock
  - ipython
  - protobuf
  - pyyaml
  - regex
  - tokenizers
  - transformers
  - datasets
  - rich
  - pip:
      - accelerate
      - peft
      - tensorboard
      - ninja
      - werkzeug
      - markdown
      - hjson
      - pydantic
      - pydantic-core
      - types-python-dateutil
      - uri-template
      - webcolors
      - jsonpointer
      - grpcio
      - fqdn
      - isoduration

